export type DoctorRecord = {
  id: string;
  name: string;
  specialty: string;
  degrees: string;
  experience: string; // e.g., "7 Years"
  visitingDays: string;
  timings: string;
  consultationFee: string;
  image: string;
  slug: string;
  seoTitle: string;
  metaDescription: string;
  focusKeyword?: string;
  about?: string;
};

export const doctorsData: DoctorRecord[] = [
  // CSV-ordered doctors
  {
    id: "1",
    name: "Dr. B G Mahesh",
    specialty: "Radiology",
    degrees: "MBBS, MD, FRGUHS",
    experience: "4 Years",
    visitingDays: "Mon–Sat",
    timings: "9AM - 5PM",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR. B.G MAHESH.png",
    slug: "dr-b-g-mahesh-radiology",
    seoTitle: "Dr. B G Mahesh – Radiology at Maiya Hospital",
    metaDescription: "Meet Dr. B G Mahesh, a Radiology specialist with 4 years of experience. Available Mon–Sat from 9AM - 5PM at Maiya Hospital.",
    focusKeyword: "Dr. B G Mahesh Radiology in Bangalore",
    about: "Dr. B G Mahesh is an experienced radiology specialist. Available Mon–Sat, 9AM - 5PM at Maiya Hospital."
  },
  {
    id: "2",
    name: "Dr. Shantharaj A",
    specialty: "Paediatrics",
    degrees: "MBBS, MD, DCH, FIAP",
    experience: "35 Years",
    visitingDays: "Mon, Tue, Thu, Fri",
    timings: "10AM - 1PM",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR SHANTHARAJ.png",
    slug: "dr-shantharaj-a-paediatrics",
    seoTitle: "Dr. Shantharaj A – Paediatrics at Maiya Hospital",
    metaDescription: "Meet Dr. Shantharaj A, a Paediatrics specialist with 35 years of experience. Available Mon, Tue, Thu, Fri from 10AM - 1PM.",
    focusKeyword: "Dr. Shantharaj A Paediatrics in Bangalore",
    about: "Dr. Shantharaj A specializes in paediatrics with over three decades of experience."
  },
  {
    id: "3",
    name: "Dr. Sudhamathy Kannan",
    specialty: "Obstetrics & Gynaecology",
    degrees: "MBBS, DGO",
    experience: "35 Years",
    visitingDays: "Mon–Sat",
    timings: "11AM - 1PM",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR SUDHAMATHY KANNAN.png",
    slug: "dr-sudhamathy-kannan-obstetrics-and-gynaecology",
    seoTitle: "Dr. Sudhamathy Kannan – Obstetrics & Gynaecology",
    metaDescription: "Meet Dr. Sudhamathy Kannan, Obstetrics & Gynaecology specialist with 35 years experience. Available Mon–Sat 11AM - 1PM.",
    focusKeyword: "Dr. Sudhamathy Kannan Obstetrics Gynaecology Bangalore",
    about: "Dr. Sudhamathy Kannan provides comprehensive obstetrics and gynaecology care with 35 years of experience."
  },
  {
    id: "4",
    name: "Dr. Sudha Gujar",
    specialty: "Anaesthesia",
    degrees: "MBBS, DA",
    experience: "35 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR SUDHA GURJAR.png",
    slug: "dr-sudha-gujar-anaesthesia",
    seoTitle: "Dr. Sudha Gujar – Anaesthesia at Maiya Hospital",
    metaDescription: "Meet Dr. Sudha Gujar, Anaesthesia specialist with 35 years of experience. Appointment Only.",
    focusKeyword: "Dr. Sudha Gujar Anaesthesia Bangalore",
    about: "Dr. Sudha Gujar is an experienced anaesthesia specialist available by appointment."
  },
  {
    id: "5",
    name: "Dr. Mahendra Jain",
    specialty: "Urology",
    degrees: "MBBS, MS, M.CH, DNB",
    experience: "25 Years",
    visitingDays: "Mon–Sat",
    timings: "4:30PM - 5:30PM",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR MAHENDRA JAIN.png",
    slug: "dr-mahendra-jain-urology",
    seoTitle: "Dr. Mahendra Jain – Urology at Maiya Hospital",
    metaDescription: "Meet Dr. Mahendra Jain, Urology specialist with 25 years of experience. Mon–Sat 4:30PM - 5:30PM.",
    focusKeyword: "Dr. Mahendra Jain Urology Bangalore",
    about: "Dr. Mahendra Jain provides expert urology care with over two decades of experience."
  },
  {
    id: "6",
    name: "Dr. Raghuveer Karanth",
    specialty: "General Medicine",
    degrees: "MBBS, DNB",
    experience: "20 Years",
    visitingDays: "Mon–Sat",
    timings: "12:30PM - 1:30PM & 8:30PM - 9:30PM",
    consultationFee: "₹500",
    image: "/new doctor profiles/DR RAGHUVEER KARANTH.png",
    slug: "dr-raghuveer-karanth-general-medicine",
    seoTitle: "Dr. Raghuveer Karanth – General Medicine",
    metaDescription: "Meet Dr. Raghuveer Karanth, General Medicine specialist with 20 years experience. Mon–Sat 12:30PM - 1:30PM & 8:30PM - 9:30PM.",
    focusKeyword: "Dr. Raghuveer Karanth General Medicine Bangalore",
    about: "Dr. Raghuveer Karanth offers comprehensive general medicine consultations."
  },
  {
    id: "7",
    name: "Dr. Usha Nandini",
    specialty: "Dentistry",
    degrees: "BDS",
    experience: "15 Years",
    visitingDays: "Mon–Sat",
    timings: "10AM - 1PM & 5PM - 7PM",
    consultationFee: "₹400",
    image: "/new doctor profiles/DR USHA NANDINI.png",
    slug: "dr-usha-nandini-dentistry",
    seoTitle: "Dr. Usha Nandini – Dentistry at Maiya Hospital",
    metaDescription: "Meet Dr. Usha Nandini, Dentistry specialist with 15 years of experience. Mon–Sat 10AM - 1PM & 5PM - 7PM.",
    focusKeyword: "Dr. Usha Nandini Dentist Bangalore",
    about: "Dr. Usha Nandini provides dental care with a patient-first approach."
  },
  {
    id: "8",
    name: "Dr. Akshay Dhanda",
    specialty: "Orthopaedics",
    degrees: "MBBS, MS, DNB(ORTHO), FRGUHS",
    experience: "10 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹400",
    image: "/new doctor profiles/DR AKSHAY DHANDA.jpg",
    slug: "dr-akshay-dhanda-orthopaedics",
    seoTitle: "Dr. Akshay Dhanda – Orthopaedics at Maiya Hospital",
    metaDescription: "Meet Dr. Akshay Dhanda, Orthopaedics specialist with 10 years experience. Appointment Only.",
    focusKeyword: "Dr. Akshay Dhanda Orthopaedics Bangalore",
    about: "Dr. Akshay Dhanda is an orthopaedics specialist available by appointment."
  },
  {
    id: "9",
    name: "Dr. Manohar Rao H R",
    specialty: "Orthopaedics",
    degrees: "MBBS, MS, DNB(ORTHO), FIJR",
    experience: "9 Years",
    visitingDays: "Mon–Sat",
    timings: "5PM - 7PM",
    consultationFee: "₹400",
    image: "/new doctor profiles/DR MANOHAR RAO.jpg",
    slug: "dr-manohar-rao-orthopaedics",
    seoTitle: "Dr. Manohar Rao – Orthopaedics at Maiya Hospital",
    metaDescription: "Meet Dr. Manohar Rao, Orthopaedics specialist with 9 years experience. Mon–Sat 5PM - 7PM.",
    focusKeyword: "Dr. Manohar Rao Orthopaedics Bangalore",
    about: "Dr. Manohar Rao treats a wide spectrum of orthopaedic conditions."
  },
  {
    id: "10",
    name: "Dr. Yashaswi",
    specialty: "E.N.T",
    degrees: "MBBS, DLO",
    experience: "15 Years",
    visitingDays: "Mon–Tue, Thu–Sat",
    timings: "6PM - 7PM",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR YASHASWI.png",
    slug: "dr-yashaswi-ent",
    seoTitle: "Dr. Yashaswi – E.N.T at Maiya Hospital",
    metaDescription: "Meet Dr. Yashaswi, ENT specialist with 15 years experience. Mon–Tue, Thu–Sat 6PM - 7PM.",
    focusKeyword: "Dr. Yashaswi ENT Bangalore",
    about: "Dr. Yashaswi provides comprehensive ENT care."
  },
  {
    id: "11",
    name: "Dr. Chethan Pai",
    specialty: "E.N.T",
    degrees: "MBBS, DLO",
    experience: "15 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹500",
    image: "/placeholder.svg",
    slug: "dr-chethan-pai-ent",
    seoTitle: "Dr. Chethan Pai – E.N.T at Maiya Hospital",
    metaDescription: "Meet Dr. Chethan Pai, ENT specialist with 15 years experience. Appointment Only.",
    focusKeyword: "Dr. Chethan Pai ENT Bangalore",
    about: "Dr. Chethan Pai is an ENT specialist available by appointment."
  },
  {
    id: "12",
    name: "Dr. Chandra Shekar H S",
    specialty: "Orthopaedics",
    degrees: "MBBS, MS, FIJR",
    experience: "40 Years",
    visitingDays: "Mon–Sat",
    timings: "12PM - 1PM",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR CHANDRASHEKAR H S.jpg",
    slug: "dr-chandra-shekar-h-s-orthopaedics",
    seoTitle: "Dr. Chandra Shekar H S – Orthopaedics",
    metaDescription: "Meet Dr. Chandra Shekar H S, Orthopaedics specialist with 40 years experience. Mon–Sat 12PM - 1PM.",
    focusKeyword: "Dr. Chandra Shekar HS Orthopaedics Bangalore",
    about: "Dr. Chandra Shekar H S is a senior orthopaedics specialist."
  },
  {
    id: "13",
    name: "Dr. Rahna Ameen",
    specialty: "Physiotherapy",
    degrees: "BPT, MIAP",
    experience: "10 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹500",
    image: "/new doctor profiles/RAHNA.jpg",
    slug: "dr-rahna-ameen-physiotherapy",
    seoTitle: "Dr. Rahna Ameen – Physiotherapy",
    metaDescription: "Meet Dr. Rahna Ameen, Physiotherapy specialist with 10 years experience. Appointment Only.",
    focusKeyword: "Dr. Rahna Ameen Physiotherapy Bangalore",
    about: "Dr. Rahna Ameen provides physiotherapy consultations and treatments."
  },
  {
    id: "14",
    name: "Dr. Krishnappa R",
    specialty: "Surgical Oncology",
    degrees: "MBBS, MS, MCH",
    experience: "35 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR KRISHNAPPA R.png",
    slug: "dr-krishnappa-r-surgical-oncology",
    seoTitle: "Dr. Krishnappa R – Surgical Oncology",
    metaDescription: "Meet Dr. Krishnappa R, Surgical Oncology specialist with 35 years experience. Appointment Only.",
    focusKeyword: "Dr. Krishnappa R Surgical Oncology Bangalore",
    about: "Dr. Krishnappa R is a senior surgical oncologist."
  },
  {
    id: "15",
    name: "Dr. Ananth Krishna M.A",
    specialty: "Surgical Gastroenterology",
    degrees: "MBBS, MS, FSGE",
    experience: "15 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR ANANTH KRISHNA.jpeg",
    slug: "dr-ananth-krishna-ma-surgical-gastroenterology",
    seoTitle: "Dr. Ananth Krishna M.A – Surgical Gastroenterology",
    metaDescription: "Meet Dr. Ananth Krishna M.A, Surgical Gastroenterology specialist with 15 years experience. Appointment Only.",
    focusKeyword: "Dr. Ananth Krishna Surgical Gastroenterology Bangalore",
    about: "Dr. Ananth Krishna provides surgical gastroenterology care."
  },
  {
    id: "16",
    name: "Dr. P. S. Prabhakaran",
    specialty: "Surgical Oncology",
    degrees: "MBBS, MS",
    experience: "45 Years",
    visitingDays: "Mon–Sat",
    timings: "11:30AM - 12:30PM",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR PRABHAKARAN P S.png",
    slug: "dr-p-s-prabhakaran-surgical-oncology",
    seoTitle: "Dr. P. S. Prabhakaran – Surgical Oncology",
    metaDescription: "Meet Dr. P. S. Prabhakaran, Surgical Oncology specialist with 45 years experience. Mon–Sat 11:30AM - 12:30PM.",
    focusKeyword: "Dr. Prabhakaran Surgical Oncology Bangalore",
    about: "Dr. Prabhakaran is a senior surgical oncologist with decades of experience."
  },
  {
    id: "17",
    name: "Dr. Pavan Prasad",
    specialty: "Surgical Oncology",
    degrees: "MBBS, MS, DNB, MCH",
    experience: "20 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR PAVAN PRASAD.jpg",
    slug: "dr-pavan-prasad-surgical-oncology",
    seoTitle: "Dr. Pavan Prasad – Surgical Oncology",
    metaDescription: "Meet Dr. Pavan Prasad, Surgical Oncology specialist with 20 years experience. Appointment Only.",
    focusKeyword: "Dr. Pavan Prasad Surgical Oncology Bangalore",
    about: "Dr. Pavan Prasad provides surgical oncology consultations and treatments."
  },
  {
    id: "18",
    name: "Dr. Sushma B N",
    specialty: "Obstetrics & Gynaecology",
    degrees: "MBBS, MS, DGO",
    experience: "10 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR SUSHMA.jpg",
    slug: "dr-sushma-b-n-obstetrics-and-gynaecology",
    seoTitle: "Dr. Sushma B N – Obstetrics & Gynaecology",
    metaDescription: "Meet Dr. Sushma B N, Obstetrics & Gynaecology specialist with 10 years experience. Appointment Only.",
    focusKeyword: "Dr. Sushma BN Obstetrics Gynaecology Bangalore",
    about: "Dr. Sushma B N provides obstetrics and gynaecology care."
  },
  {
    id: "19",
    name: "Dr. Ishwarya B",
    specialty: "Obstetrics & Gynaecology",
    degrees: "MBBS, MS",
    experience: "10 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR ISHWARYA BHANDARI.jpg",
    slug: "dr-ishwarya-b-obstetrics-and-gynaecology",
    seoTitle: "Dr. Ishwarya B – Obstetrics & Gynaecology",
    metaDescription: "Meet Dr. Ishwarya B, Obstetrics & Gynaecology specialist with 10 years experience. Appointment Only.",
    focusKeyword: "Dr. Ishwarya B Obstetrics Gynaecology Bangalore",
    about: "Dr. Ishwarya B provides obstetrics and gynaecology consultations."
  },
  {
    id: "20",
    name: "Dr. Lakshmi V Pandit",
    specialty: "Psychiatry",
    degrees: "MBBS, DPM, BPM, DNB",
    experience: "20 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹850",
    image: "/new doctor profiles/DR LAKSHMI V PANDIT.png",
    slug: "dr-lakshmi-v-pandit-psychiatry",
    seoTitle: "Dr. Lakshmi V Pandit – Psychiatry",
    metaDescription: "Meet Dr. Lakshmi V Pandit, Psychiatry specialist with 20 years experience. Appointment Only.",
    focusKeyword: "Dr. Lakshmi Pandit Psychiatry Bangalore",
    about: "Dr. Lakshmi V Pandit is a senior psychiatrist."
  },
  {
    id: "21",
    name: "Dr. Lakshmikanth P",
    specialty: "Cardiology",
    degrees: "MBBS, MD, DM",
    experience: "30 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹800",
    image: "/new doctor profiles/DR LAKSHMIKANTH.jpg",
    slug: "dr-lakshmikanth-p-cardiology",
    seoTitle: "Dr. Lakshmikanth P – Cardiology",
    metaDescription: "Meet Dr. Lakshmikanth P, Cardiology specialist with 30 years experience. Appointment Only.",
    focusKeyword: "Dr. Lakshmikanth Cardiology Bangalore",
    about: "Dr. Lakshmikanth P provides cardiology consultations."
  },
  {
    id: "22",
    name: "Dr. Hrishikesh Vemula",
    specialty: "Cardiology",
    degrees: "MBBS, MD, DM",
    experience: "20 Years",
    visitingDays: "Mon–Sat",
    timings: "9AM - 9:30AM",
    consultationFee: "₹800",
    image: "/new doctor profiles/DR HRISHIKESH VEMULA.jpg",
    slug: "dr-hrishikesh-vemula-cardiology",
    seoTitle: "Dr. Hrishikesh Vemula – Cardiology",
    metaDescription: "Meet Dr. Hrishikesh Vemula, Cardiology specialist with 20 years experience. Mon–Sat 9AM - 9:30AM.",
    focusKeyword: "Dr. Hrishikesh Vemula Cardiology Bangalore",
    about: "Dr. Hrishikesh Vemula offers comprehensive heart care."
  },
  {
    id: "23",
    name: "Dr. Sujay Rao",
    specialty: "Neurosurgery",
    degrees: "MBBS, MS, MCH",
    experience: "35 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹1200",
    image: "/new doctor profiles/DR SUJAY RAO.png",
    slug: "dr-sujay-rao-neurosurgery",
    seoTitle: "Dr. Sujay Rao – Neurosurgery",
    metaDescription: "Meet Dr. Sujay Rao, Neurosurgery specialist with 35 years experience. Appointment Only.",
    focusKeyword: "Dr. Sujay Rao Neurosurgeon Bangalore",
    about: "Dr. Sujay Rao is a senior neurosurgeon."
  },
  {
    id: "24",
    name: "Dr. Ramesh Patel",
    specialty: "Neurology",
    degrees: "MBBS, MD, DM",
    experience: "25 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹850",
    image: "/placeholder.svg",
    slug: "dr-ramesh-patel-neurology",
    seoTitle: "Dr. Ramesh Patel – Neurology",
    metaDescription: "Meet Dr. Ramesh Patel, Neurology specialist with 25 years experience. Appointment Only.",
    focusKeyword: "Dr. Ramesh Patel Neurology Bangalore",
    about: "Dr. Ramesh Patel provides neurology consultations."
  },
  {
    id: "25",
    name: "Dr. Hari Prasad",
    specialty: "Nephrology",
    degrees: "MBBS, MS, M.CH",
    experience: "25 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹800",
    image: "/new doctor profiles/Dr. Hariprasad.jpeg",
    slug: "dr-hari-prasad-nephrology",
    seoTitle: "Dr. Hari Prasad – Nephrology",
    metaDescription: "Meet Dr. Hari Prasad, Nephrology specialist with 25 years experience. Appointment Only.",
    focusKeyword: "Dr. Hari Prasad Nephrology Bangalore",
    about: "Dr. Hari Prasad offers nephrology consultations."
  },
  {
    id: "26",
    name: "Dr. Faraz Khan",
    specialty: "General Medicine",
    degrees: "MBBS, MD",
    experience: "5 Years",
    visitingDays: "Appointment Only",
    timings: "Appointment Only",
    consultationFee: "₹400",
    image: "/placeholder.svg",
    slug: "dr-faraz-khan-general-medicine",
    seoTitle: "Dr. Faraz Khan – General Medicine",
    metaDescription: "Meet Dr. Faraz Khan, General Medicine specialist with 5 years experience. Appointment Only.",
    focusKeyword: "Dr. Faraz Khan General Medicine Bangalore",
    about: "Dr. Faraz Khan provides general medicine consultations."
  },
  {
    id: "27",
    name: "Dr. Sharmila Chennappa",
    specialty: "Obstetrics & Gynaecology",
    degrees: "MBBS, MS",
    experience: "20 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/placeholder.svg",
    slug: "dr-sharmila-chennappa-obstetrics-and-gynaecology",
    seoTitle: "Dr. Sharmila Chennappa – Obstetrics & Gynaecology",
    metaDescription: "Meet Dr. Sharmila Chennappa, Obstetrics & Gynaecology specialist with 20 years experience. Appointment Only.",
    focusKeyword: "Dr. Sharmila Chennappa Obstetrics Gynaecology Bangalore",
    about: "Dr. Sharmila Chennappa provides obstetrics and gynaecology care."
  },
  {
    id: "28",
    name: "Dr. Sravan C P",
    specialty: "Vascular Surgery",
    degrees: "MBBS, MS, MRCS",
    experience: "20 Years",
    visitingDays: "Appointment Only",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/placeholder.svg",
    slug: "dr-sravan-c-p-vascular-surgery",
    seoTitle: "Dr. Sravan C P – Vascular Surgery",
    metaDescription: "Meet Dr. Sravan C P, Vascular Surgery specialist with 20 years experience. Appointment Only.",
    focusKeyword: "Dr. Sravan CP Vascular Surgery Bangalore",
    about: "Dr. Sravan C P provides vascular surgery consultations."
  },
  {
    id: "29",
    name: "Dr. Sudhakar S",
    specialty: "Radiology",
    degrees: "MBBS, DMRD, MD",
    experience: "20 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR SUDHAKAR SAMPANGI.png",
    slug: "dr-sudhakar-s-radiology",
    seoTitle: "Dr. Sudhakar S – Radiology",
    metaDescription: "Meet Dr. Sudhakar S, Radiology specialist with 20 years experience. Appointment Only.",
    focusKeyword: "Dr. Sudhakar Radiology Bangalore",
    about: "Dr. Sudhakar S offers radiology consultations."
  },
  {
    id: "31",
    name: "Dr. Revanth",
    specialty: "Radiology",
    degrees: "MBBS, MD",
    experience: "10 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/placeholder.svg",
    slug: "dr-revanth-radiology",
    seoTitle: "Dr. Revanth – Radiology",
    metaDescription: "Meet Dr. Revanth, Radiology specialist with 10 years experience. Appointment Only.",
    focusKeyword: "Dr. Revanth Radiology Bangalore",
    about: "Dr. Revanth provides radiology consultations."
  },
  {
    id: "32",
    name: "Dr. Rakesh K",
    specialty: "Plastic Surgery",
    degrees: "MBBS, DNB, MCH",
    experience: "10 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹900",
    image: "/placeholder.svg",
    slug: "dr-rakesh-k-plastic-surgery",
    seoTitle: "Dr. Rakesh K – Plastic Surgery",
    metaDescription: "Meet Dr. Rakesh K, Plastic Surgery specialist with 10 years experience. Appointment Only.",
    focusKeyword: "Dr. Rakesh K Plastic Surgery Bangalore",
    about: "Dr. Rakesh K provides plastic surgery consultations."
  },
  {
    id: "33",
    name: "Dr. Preethan Nagappa",
    specialty: "Surgical Gastroenterology",
    degrees: "MBBS, MS",
    experience: "20 Years",
    visitingDays: "Appointment Only",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/placeholder.svg",
    slug: "dr-preethan-nagappa-surgical-gastroenterology",
    seoTitle: "Dr. Preethan Nagappa – Surgical Gastroenterology",
    metaDescription: "Meet Dr. Preethan Nagappa, Surgical Gastroenterology specialist with 20 years experience. Appointment Only.",
    focusKeyword: "Dr. Preethan Nagappa Surgical Gastroenterology Bangalore",
    about: "Dr. Preethan Nagappa provides surgical gastroenterology care."
  },
  {
    id: "34",
    name: "Dr. Arpitha B Poojary",
    specialty: "Paediatrics",
    degrees: "MBBS, MD",
    experience: "2 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/new doctor profiles/Dr Arpitha.jpeg",
    slug: "dr-arpitha-b-poojary-paediatrics",
    seoTitle: "Dr. Arpitha B Poojary – Paediatrics",
    metaDescription: "Meet Dr. Arpitha B Poojary, Paediatrics specialist with 2 years experience. Appointment Only.",
    focusKeyword: "Dr. Arpitha Poojary Paediatrics Bangalore",
    about: "Dr. Arpitha B Poojary provides paediatric care."
  },
  {
    id: "35",
    name: "Dr. Murali P",
    specialty: "Medical Oncology",
    degrees: "MBBS, MD",
    experience: "10 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹850",
    image: "/new doctor profiles/DR MURALI P.jpeg",
    slug: "dr-murali-p-medical-oncology",
    seoTitle: "Dr. Murali P – Medical Oncology",
    metaDescription: "Meet Dr. Murali P, Medical Oncology specialist with 10 years experience. Appointment Only.",
    focusKeyword: "Dr. Murali P Medical Oncology Bangalore",
    about: "Dr. Murali P provides medical oncology consultations."
  },
  {
    id: "36",
    name: "Dr. Sagar S",
    specialty: "Anaesthesia",
    degrees: "MBBS, MD",
    experience: "10 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/placeholder.svg",
    slug: "dr-sagar-s-anaesthesia",
    seoTitle: "Dr. Sagar S – Anaesthesia",
    metaDescription: "Meet Dr. Sagar S, Anaesthesia specialist with 10 years experience. Appointment Only.",
    focusKeyword: "Dr. Sagar Anaesthesia Bangalore",
    about: "Dr. Sagar S provides anaesthesia consultations."
  },
  {
    id: "37",
    name: "Dr. Ganesh Shenoy",
    specialty: "General Surgery",
    degrees: "MBBS, MS",
    experience: "15 Years",
    visitingDays: "Appointment Only",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/placeholder.svg",
    slug: "dr-ganesh-shenoy-general-surgery",
    seoTitle: "Dr. Ganesh Shenoy – General Surgery",
    metaDescription: "Meet Dr. Ganesh Shenoy, General Surgery specialist with 15 years experience. Appointment Only.",
    focusKeyword: "Dr. Ganesh Shenoy General Surgery Bangalore",
    about: "Dr. Ganesh Shenoy offers general surgery consultations."
  },
  {
    id: "38",
    name: "Dr. G L Maiya",
    specialty: "General Surgery",
    degrees: "MBBS, MS",
    experience: "30 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR G L MAIYA.png",
    slug: "dr-g-l-maiya-general-surgery",
    seoTitle: "Dr. G L Maiya – General Surgery",
    metaDescription: "Meet Dr. G L Maiya, General Surgery specialist with 30 years experience. Appointment Only.",
    focusKeyword: "Dr. G L Maiya General Surgery Bangalore",
    about: "Dr. G L Maiya provides general surgery care."
  },
  {
    id: "39",
    name: "Dr. Niranjan P",
    specialty: "General Surgery",
    degrees: "MBBS, MS",
    experience: "20 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/new doctor profiles/Dr Niranjan.jpeg",
    slug: "dr-niranjan-p-general-surgery",
    seoTitle: "Dr. Niranjan P – General Surgery",
    metaDescription: "Meet Dr. Niranjan P, General Surgery specialist with 20 years experience. Appointment Only.",
    focusKeyword: "Dr. Niranjan General Surgery Bangalore",
    about: "Dr. Niranjan P offers general surgery consultations."
  },
  {
    id: "40",
    name: "Dr. Nagaraja K",
    specialty: "General Surgery",
    degrees: "MBBS, MS",
    experience: "30 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/placeholder.svg",
    slug: "dr-nagaraja-k-general-surgery",
    seoTitle: "Dr. Nagaraja K – General Surgery",
    metaDescription: "Meet Dr. Nagaraja K, General Surgery specialist with 30 years experience. Appointment Only.",
    focusKeyword: "Dr. Nagaraja General Surgery Bangalore",
    about: "Dr. Nagaraja K provides general surgery care."
  },
  {
    id: "41",
    name: "Dr. N T Babu",
    specialty: "Ophthalmology",
    degrees: "MBBS, DOMS",
    experience: "15 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹600",
    image: "/new doctor profiles/DR N T BABU.jpg",
    slug: "dr-n-t-babu-ophthalmology",
    seoTitle: "Dr. N T Babu – Ophthalmology",
    metaDescription: "Meet Dr. N T Babu, Ophthalmology specialist with 15 years experience. Appointment Only.",
    focusKeyword: "Dr. N T Babu Ophthalmology Bangalore",
    about: "Dr. N T Babu provides ophthalmology consultations."
  },
  {
    id: "42",
    name: "Dr. Raghu B P",
    specialty: "Pulmonology",
    degrees: "MBBS, MD",
    experience: "15 Years",
    visitingDays: "Mon–Sat",
    timings: "Appointment Only",
    consultationFee: "₹900",
    image: "/placeholder.svg",
    slug: "dr-raghu-b-p-pulmonology",
    seoTitle: "Dr. Raghu B P – Pulmonology",
    metaDescription: "Meet Dr. Raghu B P, Pulmonology specialist with 15 years experience. Appointment Only.",
    focusKeyword: "Dr. Raghu BP Pulmonology Bangalore",
    about: "Dr. Raghu B P offers pulmonology consultations."
  },
];

export default doctorsData;


